openapi: 3.0.0
info:
  title: API - Orders Clean Project
  version: 1.0.0
servers:
  - url: 'http://localhost:4003'
tags:
  - name: Order
paths:
  /api/order:
    post:
      tags:
        - Order
      summary: createOrder
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                payment: 1
                userMail: 'johnDoe@mail.com'
                status: 1
                note: Pedido de teste 2
                orderProducts:
                  - productId: 1
                    quantity: 1
                    price: 10
                  - productId: 2
                    quantity: 2
                    price: 11
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Order
      summary: getallOrders
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/order/50:
    patch:
      tags:
        - Order
      summary: pathOrder
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                orderProducts:
                  - productId: 3
                    quantity: 1
                    price: 8
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/order/35:
    delete:
      tags:
        - Order
      summary: deleteOrder
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/order/36:
    get:
      tags:
        - Order
      summary: getOrderById
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/order/filters:
    get:
      tags:
        - Order
      summary: getOrderByFilters
      parameters:
        - name: status
          in: query
          schema:
            type: integer
          example: '2'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
