apiVersion: v1
kind: Service
metadata:
  name: ms-order-service
  namespace: default
  labels:
    name: ms-order
    app: service
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 3020
    targetPort: 3020
  externalIPs:
  - 192.168.49.2
  selector:
    app: ms-order
