name: Standard workflow

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - .github/dependabot.yml
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - .github/dependabot.yml

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  dockerfile_path: '../..'
  CONTAINER_NAME: 'web'

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    name: Build and Test
    runs-on: 'ubuntu-latest'

    steps:
      - name: Set AWS credentials
        run: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
      - name: Checkout
        uses: actions/checkout@v3.5.0
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: .nvmrc
          cache: npm
          registry-url: https://npm.pkg.github.com/
      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: quality
        run: npm run test:ci