# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Standard workflow

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - .github/dependabot.yml
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - .github/dependabot.yml

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  dockerfile_path: '../..'
  CONTAINER_NAME: 'web'

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    name: Build and Test
    runs-on: 'ubuntu-latest'

    steps:
        - name: ESLint
          run: npm run lint
        - name: Test
          run: npm run test:ci
        # - name: SonarCloud
        #   uses: sonarsource/sonarcloud-github-action@master
        #   env:
        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #     SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}